### ISSUE TITLE
Cannot run the demo

### ISSUE THREAD

**Issue by Indigo2233** [oppo-us-research/NeuLF#2]
Hi, I cannot run the demo due to missing files:

```shell
$ python src/demo_rgb.py --exp_name Ollie_d8_w256 --data_dir dataset/Ollie/

>>> Using GPU: 0
Traceback (most recent call last):
  File "src/demo_rgb.py", line 210, in <module>
    unit = demo_rgb(args)
  File "src/demo_rgb.py", line 64, in __init__
    self.load_check_points()
  File "src/demo_rgb.py", line 199, in load_check_points
    print(f"Load weights from {ckpt_name}")
UnboundLocalError: local variable 'ckpt_name' referenced before assignment
```

```shell

$ python src/llffProcess.py --data_dir dataset/CanClip

Traceback (most recent call last):
  File "src/llffProcess.py", line 56, in <module>
    recenter=True, bd_factor=.75)
  File "/kaggle/working/NeuLF-main/src/load_llfff.py", line 248, in load_llff_data
    poses, bds, imgs = _load_data(basedir, factor=factor) # factor=8 downsamples original imgs by 8x
  File "/kaggle/working/NeuLF-main/src/load_llfff.py", line 64, in _load_data
    poses_arr = np.load(os.path.join(basedir, 'poses_bounds.npy'))
  File "/opt/conda/lib/python3.7/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/CanClip/poses_bounds.npy'
```

**Comment by lizhong3232** [comment]
Sorry for the confusion. We have updated our repository's files. Please let us know if the problem persists.

**Comment by Indigo2233** [comment]
Thank you for the update. But why were the directories `dataset/.../images` removed?

**Comment by lizhong3232** [comment]
> Thank you for the update. But why were the directories `dataset/.../images` removed?

The full resolution images located in dataset/.../images are often too large and may cause the git clone to fail. However, it should be noted that these high-resolution images are not utilized during training. Instead, we downsize the original image set by a factor of 4 for our experiments.

**Comment by Indigo2233** [comment]
But the removal also causes error:
```shell
$ python src/llffProcess.py --data_dir dataset/CanClip

 Traceback (most recent call last):
  File "src/llffProcess.py", line 56, in <module>
    recenter=True, bd_factor=.75)
  File "/kaggle/working/NeuLF-main/src/load_llfff.py", line 248, in load_llff_data
    poses, bds, imgs = _load_data(basedir, factor=factor) # factor=8 downsamples original imgs by 8x
  File "/kaggle/working/NeuLF-main/src/load_llfff.py", line 68, in _load_data
    img0 = [os.path.join(basedir, 'images', f) for f in sorted(os.listdir(os.path.join(basedir, 'images'))) \
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/CanClip/images'
```

**Comment by lizhong3232** [comment]
Fixed the bug caused by ignoring the full-resolution images, could you try again?
